//! Demo support shared by the egui and iced playgrounds: a curated icon set
//! from three real libraries (Lucide, Heroicons, Tabler) and the playground
//! readout (θ per subpath, residual, and a verdict on what kind of morph the
//! math found). Not published.
//!
//! Icon data is generated by `generate.mjs` from the npm packages of Lucide
//! (ISC), Heroicons (MIT) and Tabler Icons (MIT); the Geist fonts are OFL.
//! See `THIRD_PARTY_LICENSES.md`.

use std::sync::LazyLock;

use morphicons::{Icon, Plan};

mod data;

/// Geist and Geist Mono (variable weight), the morphicons.com typefaces.
/// SIL Open Font License 1.1, see `assets/OFL.txt`.
pub mod fonts {
    pub const GEIST: &[u8] = include_bytes!("../assets/Geist.ttf");
    pub const GEIST_MONO: &[u8] = include_bytes!("../assets/GeistMono.ttf");
}

/// The icon library an entry comes from.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Lib {
    Lucide,
    Heroicons,
    Tabler,
}

impl Lib {
    pub const ALL: [Lib; 3] = [Lib::Lucide, Lib::Heroicons, Lib::Tabler];

    pub fn name(self) -> &'static str {
        match self {
            Lib::Lucide => "Lucide",
            Lib::Heroicons => "Heroicons",
            Lib::Tabler => "Tabler",
        }
    }

    pub fn prefix(self) -> &'static str {
        match self {
            Lib::Lucide => "lucide",
            Lib::Heroicons => "heroicons",
            Lib::Tabler => "tabler",
        }
    }
}

type Nodes = &'static [(&'static str, &'static [(&'static str, &'static str)])];

pub(crate) struct RawIcon {
    lib: Lib,
    name: &'static str,
    nodes: Nodes,
}

/// One icon of the gallery. `id` is its index in [`entries`].
#[derive(Clone, Debug)]
pub struct Entry {
    pub id: usize,
    pub lib: Lib,
    pub name: &'static str,
    pub icon: Icon,
}

impl Entry {
    /// `lib:name`, e.g. `lucide:send`.
    pub fn key(&self) -> String {
        format!("{}:{}", self.lib.prefix(), self.name)
    }
}

static ENTRIES: LazyLock<Vec<Entry>> = LazyLock::new(|| {
    data::ICONS
        .iter()
        .filter_map(|raw| Icon::from_nodes(raw.nodes).ok().map(|icon| (raw, icon)))
        .enumerate()
        .map(|(id, (raw, icon))| Entry {
            id,
            lib: raw.lib,
            name: raw.name,
            icon,
        })
        .collect()
});

/// Every gallery icon, parsed once.
pub fn entries() -> &'static [Entry] {
    &ENTRIES
}

pub fn entry(id: usize) -> &'static Entry {
    &ENTRIES[id]
}

pub fn find(lib: Lib, name: &str) -> Option<&'static Entry> {
    ENTRIES.iter().find(|e| e.lib == lib && e.name == name)
}

/// Entries of `lib` (all libraries when `None`) whose key contains `query`.
pub fn search(lib: Option<Lib>, query: &str) -> Vec<&'static Entry> {
    let q = query.trim().to_lowercase();
    ENTRIES
        .iter()
        .filter(|e| lib.is_none_or(|l| e.lib == l))
        .filter(|e| q.is_empty() || e.key().contains(&q))
        .collect()
}

/// The starting "your set" row, like the website's.
pub fn default_set() -> Vec<usize> {
    [
        "x",
        "plus",
        "arrow-right",
        "arrow-down",
        "check",
        "chevron-down",
        "heart",
        "star",
    ]
    .iter()
    .filter_map(|n| find(Lib::Lucide, n).map(|e| e.id))
    .collect()
}

/// What the math says about a pair.
#[derive(Clone, Debug, PartialEq)]
pub struct Readout {
    /// `heart → star`
    pub pair: String,
    /// `θ [33°]  res 0.219`
    pub math: String,
    /// `rotation + residual`, `pure rotation, emergent`…
    pub verdict: String,
    /// True for a pure (residual-free) rotation.
    pub pure: bool,
}

/// Plans `from → to` rest to rest and classifies the result, with the same
/// thresholds as upstream's playground.
pub fn readout(from: &Entry, to: &Entry) -> Readout {
    let a = from.icon.samples();
    let b = to.icon.samples();
    let plan = Plan::new(a, b);
    let items = plan.items();
    let shown: Vec<String> = items
        .iter()
        .take(6)
        .map(|it| format!("{}°", it.theta().to_degrees().round() as i64))
        .collect();
    let more = if items.len() > 6 {
        format!(" +{}", items.len() - 6)
    } else {
        String::new()
    };
    let max_res = items.iter().map(|it| it.residual()).fold(0.0, f64::max);
    let max_theta = items.iter().map(|it| it.theta().abs()).fold(0.0, f64::max);
    let (mut verdict, pure) = if max_res < 0.03 && max_theta > 0.09 {
        ("pure rotation, emergent".to_string(), true)
    } else if max_res < 0.03 {
        ("pure similarity".to_string(), false)
    } else if max_res < 0.3 {
        ("rotation + residual".to_string(), false)
    } else {
        ("coordinate morph, aligned frame".to_string(), false)
    };
    if a.len() != b.len() {
        verdict.push_str(" · cell division");
    }
    Readout {
        pair: format!("{} → {}", from.name, to.name),
        math: format!("θ [{}{more}]  res {max_res:.3}", shown.join(" ")),
        verdict,
        pure,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_icon_parses() {
        assert_eq!(entries().len(), data::ICONS.len());
        for lib in Lib::ALL {
            assert!(entries().iter().filter(|e| e.lib == lib).count() > 40);
        }
    }

    #[test]
    fn readout_matches_the_website() {
        let l = |n| find(Lib::Lucide, n).unwrap();
        let r = readout(l("arrow-right"), l("arrow-down"));
        assert_eq!(r.pair, "arrow-right → arrow-down");
        assert_eq!(r.math, "θ [90° 90°]  res 0.000");
        assert_eq!(r.verdict, "pure rotation, emergent");
        assert!(
            readout(l("star"), l("menu"))
                .verdict
                .ends_with("· cell division")
        );
    }

    #[test]
    fn cross_library_morphs_are_finite() {
        let all = entries();
        let mut out;
        for (i, a) in all.iter().enumerate().step_by(7) {
            let b = &all[(i * 31 + 17) % all.len()];
            let plan = Plan::new(a.icon.samples(), b.icon.samples());
            out = plan.outputs();
            plan.interpolate(0.5, &mut out);
            assert!(
                out.iter().flatten().all(|p| p.is_finite()),
                "{} → {}",
                a.key(),
                b.key()
            );
        }
    }

    #[test]
    fn search_filters_by_library_and_text() {
        assert!(
            search(Some(Lib::Tabler), "rocket")
                .iter()
                .all(|e| e.lib == Lib::Tabler)
        );
        assert!(!search(None, "lucide:send").is_empty());
        assert_eq!(search(None, "").len(), entries().len());
    }
}
